---
title: "Figures for review"
author: "Jitao david Zhang"
date: "18/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.height = 4, 
                      fig.width = 4,
                      fig.path = "figures/review-",
                      dev = c("png", "pdf"))
library(ribiosUtils)
library(ribiosIO)
library(ggplot2)
library(ggpmisc)
library(ggthemes)
library(gridExtra)
library(readr)
library(tidyr)
library(dplyr)
library(openxlsx)
library(cowplot)
ggplot2::theme_set(theme_minimal(base_size=14))
```

## Publication by keywords and by year

```{r pubByYear, fig.width=6, fig.height=3}
pubmed_wide <- read_csv("data/2022-06-PubMed-by-Year.csv")
pubmed <- pubmed_wide %>%
  tidyr::pivot_longer(cols=c("causal drug discovery",
                      "machine learning drug discovery",
                      "artificial intelligence drug discovery"),
               names_to="keyword") %>%
  dplyr::mutate(keyword = gsub(" drug discovery", "", keyword)) %>%
  dplyr::mutate(keyword = replace(keyword, keyword=="causal",
                                  "causal inference")) %>%
  dplyr::mutate(keyword=factor(keyword,
                        c("causal inference", 
                          "machine learning", "artificial intelligence")))
pubByYear <- ggplot(pubmed, 
       aes(x=Year, y=value, color=keyword, group=keyword)) +
  geom_point() +
  geom_path() +
  xlim(1990, 2022) +
  ylab("Publications per 100,000") +
  scale_color_manual(values=c("limegreen", "orange", "red"))
print(pubByYear)
```

## Publication by activities of drug discovery and development

```{r}
activity <- openxlsx::read.xlsx("data/2022-05-31-causal-inference-in-drug-discovery-PubMed.xlsx", cols=1:5) %>% dplyr::filter(Manual.classification != "Other")

activity_summ <- activity %>% dplyr::select(Manual.classification) %>%
  dplyr::group_by(Manual.classification) %>%
  dplyr::summarise(n=dplyr::n()) %>%
  dplyr::arrange(desc(n)) %>%
  dplyr::mutate(Manual.classification = ribiosUtils::ofactor(Manual.classification))
```

```{r activity, fig.height=5, fig.width=6}
activityPlot <- ggplot(activity_summ, aes(x=Manual.classification, y=n)) +
  geom_bar(stat="identity", fill="lightblue", col="black") +
  ##theme(axis.text.x = element_text(angle=90)) +
  xlab("Activities") + ylab("Publications") +
  coord_flip()
print(activityPlot)
```

```{r CombinedPublicationFigure, fig.height=7, fig.width=6}
ggdraw() + 
  draw_plot(pubByYear, x=0.05, y=.625, width=.95, height=0.375) +
  draw_plot(activityPlot, x=0.05, y=0.0, width=.95, height=0.625, scale=1) +
  draw_plot_label(label = c("A", "B"), size = 15,
                  x = c(0, 0), 
                  y = c(1, 0.625))
```
```{r CombinedPublicationFigureHor, fig.height=3, fig.width=9}
ggdraw() + 
  draw_plot(pubByYear +
              theme(legend.position = c(0.4,0.85),
                    legend.title = element_blank()), 
            x=0.05, y=0, width=.35, height=1) +
  draw_plot(activityPlot, x=0.4, y=0.0, width=.6, height=1, scale=1) +
  draw_plot_label(label = c("A", "B"), size = 15,
                  x = c(0, 0.4), 
                  y = c(1, 1))
```

